# Lesson 4 Задание на повторение материала

1.	Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
import numpy as np

In [34]:
a = np.arange(12, 24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


2.	Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [35]:
b = a.reshape(3, 4)
print(b)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [7]:
c = a.reshape(4, 3)
print(c)

[[12. 13. 14.]
 [15. 16. 17.]
 [18. 19. 20.]
 [21. 22. 23.]]


In [8]:
d = a.reshape(2, 6)
print(d)

[[12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


In [9]:
e = a.reshape(6, 2)
print(e)

[[12. 13.]
 [14. 15.]
 [16. 17.]
 [18. 19.]
 [20. 21.]
 [22. 23.]]


In [10]:
f = a.reshape(12, 1)
print(f)

[[12.]
 [13.]
 [14.]
 [15.]
 [16.]
 [17.]
 [18.]
 [19.]
 [20.]
 [21.]
 [22.]
 [23.]]


3.	Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [16]:
g = a.reshape(3, -1)
print(g)

[[12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]]


In [17]:
h = a.reshape(4, -1)
print(h)

[[12. 13. 14.]
 [15. 16. 17.]
 [18. 19. 20.]
 [21. 22. 23.]]


In [18]:
i = a.reshape(2, -1)
print(i)

[[12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


In [19]:
j = a.reshape(-1, 2)
print(j)

[[12. 13.]
 [14. 15.]
 [16. 17.]
 [18. 19.]
 [20. 21.]
 [22. 23.]]


In [20]:
k = a.reshape(-1, 1)
print(k)

[[12.]
 [13.]
 [14.]
 [15.]
 [16.]
 [17.]
 [18.]
 [19.]
 [20.]
 [21.]
 [22.]
 [23.]]


4.	Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

ответ: нет, т.к. строки здесь это массивы, состоящие из 1 элемента

5.	Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [25]:
a = np.random.randn(3, 4)

print(a)

[[-1.25848988  1.96545606 -0.64957191 -0.35313486]
 [ 0.61538398 -0.97754699 -0.62015387 -0.84858631]
 [ 0.77886402  0.11183441  0.13831858 -0.48896264]]


In [27]:
b = a.flatten()
print(b)

[-1.25848988  1.96545606 -0.64957191 -0.35313486  0.61538398 -0.97754699
 -0.62015387 -0.84858631  0.77886402  0.11183441  0.13831858 -0.48896264]


In [29]:
a.size == b.size

True

6.	Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [31]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


7.	Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [36]:
b = np.arange(20, 1, -2).reshape(1,10)
print(b)

[[20 18 16 14 12 10  8  6  4  2]]


a - одномерный, b - двумерный массив

8.	Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [52]:
a = np.zeros((2, 2))
print (a)

[[0. 0.]
 [0. 0.]]


In [53]:
b = np.ones((3, 2))
print (b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [54]:
v = np.vstack((a, b))
print(v)
v.size

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


10

9.	Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [59]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [60]:
A = a.reshape(4, 3)
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [61]:
At = A.T
print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [62]:
B = A.dot(At)
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [63]:
B.size

16

In [64]:
print(np.linalg.det(B))

0.0


поскольку определитель матрицы В равен 0, то вычислить обратную матрицу для В невозможно.


In [66]:
# пруф:

B_inv = np.linalg.inv(B)

print(B_inv)

LinAlgError: Singular matrix

10. Инициализируйте генератор случайных чисел с помощью объекта seed, равного 42.

In [70]:
np.random.seed(42)


11.	Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [74]:
c = np.random.randint(0, 16, (1, 16))
print(c)

[[ 3 12 14 10  7 12  4  6  9  2  6 10 10  7  4  3]]


12.	Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [75]:
C = c.reshape(4, 4)
print(C)

[[ 3 12 14 10]
 [ 7 12  4  6]
 [ 9  2  6 10]
 [10  7  4  3]]


In [78]:
D = np.add(B, C*10)
print(D)

[[ 35 134 163 132]
 [ 84 170 126 182]
 [113 106 209 312]
 [132 192 252 332]]


In [79]:
print(np.linalg.det(D))

21320000.000000034


In [80]:
r = np.linalg.matrix_rank(D)
print(r)

4


In [81]:
D_inv = np.linalg.inv(D)

print(D_inv)

[[-0.0421257  -0.04781989 -0.07423077  0.11272233]
 [ 0.00713133  0.01837899  0.00807692 -0.02050094]
 [-0.00235084 -0.03018386 -0.02807692  0.04386679]
 [ 0.01440901  0.03129456  0.04615385 -0.06324578]]


13.	Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [82]:
D_inv = np.where(D_inv < 0, 0, 1)

print(D_inv)

[[0 0 0 1]
 [1 1 1 0]
 [0 0 0 1]
 [1 1 1 0]]


In [89]:
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [90]:
print(C)

[[ 3 12 14 10]
 [ 7 12  4  6]
 [ 9  2  6 10]
 [10  7  4  3]]


In [91]:
E = np.where(D_inv == 1, B, C)
print(E)

[[  3  12  14  32]
 [ 14  50  86   6]
 [  9   2   6 212]
 [ 32 122 212   3]]
